function jsonFileContent = exportSignalAnalysis(specData)
    globalEmissions = [];

    for ii = 1:numel(specData)
        emissions = table( ...
            'Size', [0, 15], ...
            'VariableNames', { ...
                'freqCenter', 'bandWidthkHz', 'channelFrequency', 'channelBandWidthkHz', 'monitoringLatitude', 'monitoringLongitude', ...
                'emissionType', 'regulatory', 'service', 'station', 'description', 'annotation', 'distance', 'irregular', 'riskLevel' ...
            }, ...
            'VariableTypes', { ...
                'double', 'double', 'double', 'double', 'double', 'double', ...
                'cell', 'cell', 'int16', 'int32', 'cell', 'string', 'double', 'cell', 'cell' ...
            } ...
        );

        for jj = 1:height(specData(ii).UserData.Emissions)
            emissions(end+1, :) = { ...
                specData(ii).UserData.Emissions.Frequency(jj), ...
                specData(ii).UserData.Emissions.BandWidthkHz(jj), ...
                specData(ii).UserData.Emissions.ChannelAssigned(jj).UserModified.Frequency, ...
                specData(ii).UserData.Emissions.ChannelAssigned(jj).UserModified.ChannelBW, ...
                specData(ii).GPS.Latitude, ...
                specData(ii).GPS.Longitude, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.EmissionType, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.Regulatory, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.Service, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.Station, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.Description, ...
                specData(ii).UserData.Emissions.Description(jj), ...
                round(specData(ii).UserData.Emissions.Classification(jj).UserModified.Distance, 1), ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.Irregular, ...
                specData(ii).UserData.Emissions.Classification(jj).UserModified.RiskLevel ...
            };
        end

        globalEmissions = [globalEmissions; emissions];
    end

    % Força arredondamento de valores numéricos, evitando que no
    % JSON apareça algo como "79.4000015258789", por exemplo.
    globalEmissions(:, {'freqCenter', 'channelFrequency'}) = round(globalEmissions(:, {'freqCenter', 'channelFrequency'}), 3);
    globalEmissions(:, {'bandWidthkHz', 'channelBandWidthkHz'}) = round(globalEmissions(:, {'bandWidthkHz', 'channelBandWidthkHz'}), 1);
    globalEmissions(:, {'monitoringLatitude', 'monitoringLongitude'}) = round(globalEmissions(:, {'monitoringLatitude', 'monitoringLongitude'}), 6);

    jsonFileContent = jsonencode(globalEmissions, 'PrettyPrint', true, 'ConvertInfAndNaN', false);
end