classdef (Abstract) Table

    methods (Static)
        %-----------------------------------------------------------------%
        function Table = Algorithms(analyzedData)
            specData = analyzedData.InfoSet;

            Table = table('Size', [3, 2],                    ...
                          'VariableTypes', {'cell', 'cell'}, ...
                          'VariableNames', {'Algorithm', 'Parameters'});
                
            % Ocupação
            if isempty(specData.UserData.Emissions)
                occupancy = {sprintf('Método: %s',       specData.UserData.ReportAlgorithms.Occupancy.Method); ...
                             sprintf('- Parâmetros: %s', jsonencode(structUtil.delEmptyFields(specData.UserData.ReportAlgorithms.Occupancy, {'Method'})))};
        
            else        
                occupancyList = arrayfun(@(x) x.Occupancy, specData.UserData.Emissions.Algorithms, 'UniformOutput', false);
                [occupancyType, ~, occupancyTypeIdx] = unique(occupancyList, 'stable');
        
                occupancy = {};        
                for ii = 1:numel(occupancyType)
                    sOCCType   = jsondecode(occupancyType{ii});
                    sOCCIndex  = find(occupancyTypeIdx == ii);
                    peaksLabel = strjoin(string(sOCCIndex), ', ');
            
                    occupancy(end+1:end+3,1) = {sprintf('Método: %s',       sOCCType.Method);                                                                     ...
                                                sprintf('- Parâmetros: %s', jsonencode(structUtil.delEmptyFields(sOCCType, {'Method'}), "ConvertInfAndNaN", false)); ...
                                                sprintf('- Emissões: %s',   peaksLabel)};
            
                    if (numel(occupancyType) > 1) && (ii < numel(occupancyType))
                        occupancy(end+1) = {'&nbsp;'};
                    end
                end
            end
        
            % Detecção
            bandLimitsStatus = specData.UserData.bandLimitsStatus;
            bandLimitsTable  = specData.UserData.bandLimitsTable;
            if ~bandLimitsStatus || isempty(bandLimitsTable)
                bandLimits = sprintf('Faixa sob análise: %.3f - %.3f MHz', specData.MetaData.FreqStart / 1e+6, ...
                                                                           specData.MetaData.FreqStop  / 1e+6);    
            else
                bandLimits = {};
                for ii = 1:height(bandLimitsTable)
                    bandLimits{end+1} = sprintf('%.3f - %.3f MHz', bandLimitsTable.FreqStart(ii), ...
                                                                   bandLimitsTable.FreqStop(ii));
                end
                bandLimits = sprintf('Faixa sob análise: %s', strjoin(bandLimits, ', '));
            end
        
            % Essa operação aqui surgiu por conta da inclusão de emissões através
            % de arquivos (seja ele gerado pelo ROMES ou outra ferramenta).
            detectionList  = arrayfun(@(x) x.Detection, specData.UserData.Emissions.Algorithms, 'UniformOutput', false);
            [detectionType, ~, detectionTypeIdx] = unique(detectionList, 'stable');
        
            if specData.UserData.ReportAlgorithms.Detection.ManualMode
                detection = {'Detecção limitada às emissoes identificadas no modo PLAYBACK do appAnalise'; bandLimits};
            else
                detection = {'Detecção não limitada às emissões identificadas no modo PLAYBACK do appAnalise'; bandLimits; ...
                             sprintf('Algoritmo: %s',  specData.UserData.ReportAlgorithms.Detection.Algorithm);       ...
                             sprintf('- Parâmetros: %s', jsonencode(specData.UserData.ReportAlgorithms.Detection.Parameters, "ConvertInfAndNaN", false))};
            end
        
            if ~isempty(detectionType)
                detection = [detection; '&nbsp;'];
            end
        
            for ii =1:numel(detectionType)
                sOCCType   = jsondecode(detectionType{ii});
                sOCCIndex  = find(detectionTypeIdx == ii);
                peaksLabel = strjoin(string(sOCCIndex), ', ');
        
                if isfield(sOCCType, 'Parameters')
                    detection(end+1:end+3,1) = {sprintf('Algoritmo: %s',    sOCCType.Algorithm);                                         ...
                                                sprintf('- Parâmetros: %s', jsonencode(sOCCType.Parameters, "ConvertInfAndNaN", false)); ...
                                                sprintf('- Emissões: %s',   peaksLabel)};
                else
                    detection(end+1:end+2,1) = {sprintf('Algoritmo: %s',    sOCCType.Algorithm); ...
                                                sprintf('- Emissões: %s',   peaksLabel)};
                end
        
                if (numel(detectionType) > 1) && (ii < numel(detectionType))
                    detection(end+1) = {'&nbsp;'};
                end
            end
            
            % Classificação
            classification = {sprintf('Algoritmo: %s',  specData.UserData.ReportAlgorithms.Classification.Algorithm); ...
                              sprintf('- Parâmetros: %s', jsonencode(specData.UserData.ReportAlgorithms.Classification.Parameters, "ConvertInfAndNaN", false))};
        
        
            Table(1,:) = {'Ocupação',                  occupancy};
            Table(2,:) = {'Detecção de emissões',      detection};
            Table(3,:) = {'Classificação de emissões', classification};
        end

        %-----------------------------------------------------------------%
        function Table = EmissionPerBand(analyzedData)
            specData = analyzedData.InfoSet;
            Table = specData.UserData.Emissions;

            % Mesclar com informações em Classification e Measure e
            % Description...
        end

        %-----------------------------------------------------------------%
        % TABELAS PARA SHAREPOINT (SCARAB)
        %-----------------------------------------------------------------%
        % function jsonFileContent = scarabJsonFile(projectData, context, correlationKey, executionMode, issueDetails, generalSettings, EMFieldObj, referenceTable)
        %     entityGroupName = projectData.modules.(context).ui.entity.name;
        %     entityGroupId = projectData.modules.(context).ui.entity.id;
        % 
        %     jsonFileContent = struct( ...
        %         'schemaVersion', 1, ...
        %         'clientName', class.Constants.appName, ...
        %         'clientVersion', class.Constants.appVersion, ...
        %         'clientExecutionMode', executionMode, ...
        %         'auditorName', issueDetails.usuario.nome, ...
        %         'auditorEmail', issueDetails.usuario.email, ...
        %         'auditorDepartment', issueDetails.usuario.unidade, ...
        %         'auditorJobTitle', issueDetails.usuario.funcao, ...
        %         'project', struct( ...
        %             'correlationKey', correlationKey, ...
        %             'system', projectData.modules.(context).ui.system, ...
        %             'issue', projectData.modules.(context).ui.issue, ...
        %             'context', context, ...
        %             'entityGroupName', entityGroupName, ...
        %             'entityGroupId', entityGroupId, ...
        %             'unit', projectData.modules.(context).ui.unit ...
        %         ), ...
        %         'rawFiles', [] ...
        %     );
        % 
        %     % RAWFILES
        %     rawFiles = table( ...
        %         'Size', [numel(EMFieldObj), 17], ...
        %         'VariableNames', {'correlationKey', 'fileName', 'sensorManufacturer', 'sensorModel', 'sensorSerialNumber', 'measurementStartTime', 'measurementEndTime', 'measurementCount', 'electricFieldMin', 'electricFieldMax', 'centralPointLat', 'centralPointLng', 'boundingBoxLatMin', 'boundingBoxLatMax', 'boundingBoxLngMin', 'boundingBoxLngMax', 'coveredDistanceKm'}, ...
        %         'VariableTypes', {'cell', 'cell', 'cell', 'cell', 'cell', 'cell', 'cell', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'} ...
        %     );
        % 
        %     for ii = 1:numel(EMFieldObj)
        %         rawFiles(ii, :) = { ...
        %             correlationKey,                     ...
        %             EMFieldObj(ii).FileName,            ...
        %             EMFieldObj(ii).Sensor,              ...
        %             EMFieldObj(ii).MetaData.Model,      ...
        %             EMFieldObj(ii).MetaData.Serial,     ...
        %             datestr(EMFieldObj(ii).Data.Timestamp(1),   'yyyymmdd HH:MM:SS'), ...
        %             datestr(EMFieldObj(ii).Data.Timestamp(end), 'yyyymmdd HH:MM:SS'), ...
        %             EMFieldObj(ii).Measures,            ...
        %             EMFieldObj(ii).FieldValueLimits(1), ...
        %             EMFieldObj(ii).FieldValueLimits(2), ...
        %             EMFieldObj(ii).Latitude,            ...
        %             EMFieldObj(ii).Longitude,           ...
        %             EMFieldObj(ii).LatitudeLimits(1),   ...
        %             EMFieldObj(ii).LatitudeLimits(2),   ...
        %             EMFieldObj(ii).LongitudeLimits(1),  ...
        %             EMFieldObj(ii).LongitudeLimits(2),  ...
        %             EMFieldObj(ii).CoveredDistanceKm ...
        %         };
        %     end
        % 
        %     jsonFileContent.rawFiles = rawFiles;
        % 
        %     % STATIONTABLE & POINTSTABLE
        %     referenceTable = model.ProjectBase.prepareReferenceTableToExport(context, referenceTable, generalSettings);
        %     referenceTable.('correlationKey')(:) = {correlationKey};
        %     referenceTable = movevars(referenceTable, 'correlationKey', 'Before', 1);
        % 
        %     switch context
        %         case 'MONITORINGPLAN'
        %             jsonFileContent.stationTable = referenceTable;
        % 
        %         case 'EXTERNALREQUEST'
        %             jsonFileContent.pointsTable  = referenceTable;
        %     end
        % 
        %     jsonFileContent = jsonencode(jsonFileContent, 'PrettyPrint', true);
        % end
        % 
        % %-----------------------------------------------------------------%
        % function teamsFileContent = scarabTeamsFileContent(issueDetails, sharepointFileList)
        %     teamsFileContent = struct( ...
        %         'schemaVersion', 1, ...
        %         'clientName', class.Constants.appName, ...
        %         'auditorName', issueDetails.usuario.nome, ...
        %         'auditorEmail', issueDetails.usuario.email, ...
        %         'fileNameList', {sharepointFileList} ...
        %     );
        % 
        %     teamsFileContent = jsonencode(teamsFileContent, 'PrettyPrint', true);
        % end
    end
end