classdef Project < model.ProjectCommon

    % ## model.Project (appAnalise) ##      
    % PUBLIC
    %   ├── Project
    %   |   |── restart
    %   |   └── model.ProjectBase.initializeCustomTable
    %   ├── restart
    %   │   └── contextInitialization
    %   ├── checkIfUpdateNeeded
    %   │   └── model.ProjectBase.computeProjectHash
    %   ├── save
    %   │   └── model.ProjectBase.computeProjectHash
    %   ├── load
    %   │   └── restart
    %   └── validateAuditorClassification
    % PRIVATE
    %   └── contextInitialization
    %       └── initialization (SuperClass)


    methods
        %-----------------------------------------------------------------%
        function obj = Project(mainApp, rootFolder, generalSettings)
            obj@model.ProjectCommon(mainApp, rootFolder);
            
            restart(obj, {'PLAYBACK', 'DRIVETEST', 'SIGNALANALYSIS', 'RFDATAHUB'}, 'AppStarted', generalSettings)
        end

        %-----------------------------------------------------------------%
        % ## LIFECYCLE MANAGEMENT ##
        %-----------------------------------------------------------------%
        function restart(obj, contextList, operationType, generalSettings)
            contextInitialization(obj, contextList, operationType, generalSettings)
        end

        %-----------------------------------------------------------------%
        function updateNeeded = checkIfUpdateNeeded(obj, specData)
            updateNeeded = false;
            
            if ~isempty(obj.name)
                currentPrjHash = model.ProjectBase.computeProjectHash(obj.name, obj.file, obj.modules, obj.issueDetails, obj.entityDetails, specData);
                updateNeeded   = ~isequal(obj.hash, currentPrjHash);
            end
        end

        %-----------------------------------------------------------------%
        function save(obj, context, prjName, prjFile, outputFileCompressionMode, specData)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'PLAYBACK'})}
                prjName
                prjFile
                outputFileCompressionMode
                specData
            end

            source    = class.Constants.appName;
            type      = 'ProjectData';
            version   = 1;
            userData  = [];

            prjHash   = model.ProjectBase.computeProjectHash(prjName, prjFile, obj.modules, obj.issueDetails, obj.entityDetails, specData);
            variables = struct( ...
                'name',    prjName, ...
                'hash',    prjHash, ...
                'modules', obj.modules, ...
                'issueDetails', obj.issueDetails, ...
                'entityDetails', obj.entityDetails, ...
                'specDataObj', specData ...
            );

            compressionMode = {};
            if strcmp(outputFileCompressionMode, 'Não')
                compressionMode = {'-nocompression'};
            end

            save(prjFile, 'source', 'type', 'version', 'variables', 'userData', '-mat', '-v7', compressionMode{:})

            obj.name = prjName;
            obj.file = prjFile;
            obj.hash = prjHash;
        end

        %-----------------------------------------------------------------%
        function [specDataObj, msg] = load(obj, context, fileName, generalSettings, specDataObj)
            arguments
                obj
                context (1,:) char {mustBeMember(context, {'FILE', 'PLAYBACK'})}
                fileName
                generalSettings
                specDataObj
            end

            try
                required = {'source', 'version', 'variables'};
                varsInFile = who('-file', fileName);
                if any(~ismember(required, varsInFile))
                    missing = setdiff(required, varsInFile);
                    error('Missing required variables: %s', strjoin(missing, ', '))
                end
                
                prjData = load(fileName, '-mat', required{:});
                
                if ~strcmp(class.Constants.appName, prjData.source)
                    error('File generated by a different application. Expected: %s. Found: %s.', class.Constants.appName, prjData.source)
                end
    
                switch prjData.version
                    case 1
                        restart(obj, {'PLAYBACK', 'DRIVETEST', 'SIGNALANALYSIS', 'RFDATAHUB'}, 'onProjectLoad', generalSettings)

                        obj.name = prjData.variables.name;
                        obj.file = fileName;
                        obj.hash = prjData.variables.hash;

                        contextList = {'PLAYBACK'};
                        for ii = 1:numel(contextList)
                            context = contextList{ii};

                            if isfile(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath)
                                try
                                    unzipFiles = unzip(prjData.variables.modules.(context).generatedFiles.lastZIPFullPath, generalSettings.fileFolder.tempPath);
                                    for jj = 1:numel(unzipFiles)
                                        [~, ~, unzipFileExt] = fileparts(unzipFiles{jj});
    
                                        switch lower(unzipFileExt)
                                            case '.html'
                                                obj.modules.(context).generatedFiles.lastHTMLDocFullPath = unzipFiles{jj};
                                            case '.json'
                                                obj.modules.(context).generatedFiles.lastJSONFullPath    = unzipFiles{jj};
                                            case '.xlsx'
                                                obj.modules.(context).generatedFiles.lastTableFullPath   = unzipFiles{jj};
                                            case '.teams'
                                                obj.modules.(context).generatedFiles.lastTEAMSFullPath   = unzipFiles{jj};
                                            otherwise
                                                obj.modules.(context).generatedFiles.rawFiles{end+1}     = unzipFiles{jj};
                                        end
                                    end
                                    
                                    obj.modules.(context).generatedFiles.id              = prjData.variables.modules.(context).generatedFiles.id;
                                    obj.modules.(context).generatedFiles.lastZIPFullPath = prjData.variables.modules.(context).generatedFiles.lastZIPFullPath;
                                catch 
                                end
                            end
    
                            obj.modules.(context).ui.system = prjData.variables.modules.(context).ui.system;
                            obj.modules.(context).ui.unit   = prjData.variables.modules.(context).ui.unit;
                            obj.modules.(context).ui.issue  = prjData.variables.modules.(context).ui.issue;
                            obj.modules.(context).ui.entity = prjData.variables.modules.(context).ui.entity;
        
                            reportModel = prjData.variables.modules.(context).ui.reportModel;
                            if ismember(reportModel, obj.modules.(context).ui.templates)
                                obj.modules.(context).ui.reportModel = reportModel;
                            end

                            obj.modules.(context).annotationTable = prjData.variables.modules.(context).annotationTable;
    
                            obj.modules.(context).uploadedFiles = [prjData.variables.modules.(context).uploadedFiles, obj.modules.(context).uploadedFiles];
                            [~, uniqueUploadedFilesIndexes] = unique({obj.modules.(context).uploadedFiles.hash});
                            obj.modules.(context).uploadedFiles = obj.modules.(context).uploadedFiles(uniqueUploadedFilesIndexes);
                        end

                        obj.issueDetails = [prjData.variables.issueDetails, obj.issueDetails];                        
                        
                        obj.entityDetails = [prjData.variables.entityDetails, obj.entityDetails];                        
                        [~, uniqueDetailsIndexes] = unique({obj.entityDetails.id});
                        obj.entityDetails = obj.entityDetails(uniqueDetailsIndexes);

                        % Pode ocorrer uma coincidência de fluxos que compõem
                        % o projeto e fluxos já lidos. Se evidenciado, serão
                        % mantidos os fluxos do projeto.
                        idx = ismember({specDataObj.Hash}, {prjData.variables.EMFieldObj.Hash});
                        if any(idx)
                            delete(specDataObj(idx))
                            specDataObj(idx) = [];
                        end
    
                        specDataObj = [specDataObj, prjData.variables.EMFieldObj];
    
                    otherwise
                        error('UnexpectedVersion')
                end
                msg = '';

            catch ME
                msg = ME.message;
            end
        end

        %-----------------------------------------------------------------%
        % ## VALIDATION ##
        %-----------------------------------------------------------------%
        function validateAuditorClassification(obj, context, generalSettings, varargin)
            % ...
        end
    end


    methods (Access = private)
        %-----------------------------------------------------------------%
        function contextInitialization(obj, contextList, operationType, generalSettings)
            arguments
                obj
                contextList
                operationType {mustBeMember(operationType, {'AppStarted', 'onProjectLoad', 'onProjectRestart'})}
                generalSettings
            end

            switch operationType
                case 'AppStarted'
                    initialization(obj, contextList, generalSettings)

                case {'onProjectLoad', 'onProjectRestart'}
                    % ...
            end
        end
    end
end