classdef UserData

    properties
        %-----------------------------------------------------------------%
        % Altura da antena utilizada na medição (em metros)
        AntennaHeightMeters

        % Curva de calibração aplicada às medições (ex.: fator K de antena)
        CalibrationCurve = table( ...
            'Size', [0, 4], ...
            'VariableTypes', {'cell', 'cell', 'cell', 'cell'}, ...
            'VariableNames', {'Name', 'Type', 'oldUnitLevel', 'newUnitLevel'} ...
        )

        % Índices de canalizações predefinidas disponíveis na base do app,
        % as quais são organizadas no objeto model.ChannelObj
        ChannelLibraryRelatedIndexes

        % Canalizações definidas manualmente pelo usuário
        ChannelUserDefined = struct( ...
            'Name', {}, ...
            'Band', {}, ...
            'FirstChannel', {}, ...
            'LastChannel', {}, ...
            'StepWidth', {}, ...
            'ChannelBW', {}, ...
            'FreqList', {}, ...
            'Reference', {}, ...
            'FindPeaksName', {} ...
        )

        % Subfaixas que restringem o escopo da detecção de emissões
        DetectionSubBandsEnabled = false
        DetectionSubBands = table( ...
            'Size', [0, 2], ...
            'VariableTypes', {'double', 'double'}, ...
            'VariableNames', {'FreqStart', 'FreqStop'} ...
        )

        % Tabela de emissões detectadas automaticamente ou inseridas manualmente
        Emissions = table( ...
            uint32([]), [], [], true(0,1), string.empty,                                     ...
            struct('Detection', {}, 'Classification', {}, 'Occupancy', {}, 'BandWidth', {}), ...
            struct('Level', {}, 'FCO', {}, 'FBO', {}, 'BandWidth', {}),                      ...
            struct('autoSuggested', {}, 'userModified', {}),                                 ...
            struct('autoSuggested', {}, 'userModified', {}),                                 ...
            struct('DriveTest', {}, 'RFDataHub', {}, 'SignalAnalysis', {}),                  ...
            'VariableNames', {'idxFrequency', 'Frequency', 'BW_kHz', 'isTruncated', 'Description', 'Algorithms', 'Measures', 'ChannelAssigned', 'Classification', 'auxAppData'} ...
        )

        % Define a origem/modo de cálculo da ocupação, podendo ser fluxo 
        % gerado pelo próprio sensor (RelatedIndex e SelectedIndex) ou a 
        % partir do fluxo de níveis (CacheIndex)
        OccupancyComputationMode = struct( ...
            'RelatedHashes', {{}}, ...
            'SelectedHash', '', ...
            'CacheIndex', [] ...
        )

        % Cache de ocupação com integração finita (ex.: 15, 30, 60 min),
        % gerado internamente a partir de níveis e limiar (THR)
        OccupancyFiniteIntegrationCache = struct( ...
            'Info', {}, ...
            'THR', {}, ...
            'Data', {} ...
        )

        % Resultado de ocupação por ponto de frequência com integração 
        % cumulativa, considerando todas as varreduras ("integração infinita")
        OccupancyCumulativeIntegration

        % Configurações de exibição do espectro (waterfall, persistência,
        % curvas visíveis como minhold, maxhold, clearwrite etc.)
        PlotDisplayConfig = struct( ...
            'Type', 'auto', ...
            'Parameters', [] ...
        )

        % Indica se o fluxo atual deve ser incluído no relatório
        ReportInclude = false

        % Configuração dos algoritmos automáticos executados na análise
        ReportAlgorithms = struct( ...
            'Detection', model.UserData.getFieldTemplate('DefaultAlgorithm: Detection'),      ...
            'Classification', model.UserData.getFieldTemplate('DefaultAlgorithm: Classification'), ...
            'Occupancy', model.UserData.getFieldTemplate('DefaultAlgorithm: Occupancy') ...
        )

        % Arquivos externos que podem ser anexados ao relatório
        ReportAttachments = table( ...
            'Size', [0, 4], ...
            'VariableTypes', {'cell', 'cell', 'cell', 'int8'}, ...
            'VariableNames', {'Type', 'Tag', 'Filename', 'ID'} ...
        )

        % Relação de canais, quando análise é orientada a canais (ao invés
        % de faixas de frequências)
        ReportChannels
        ReportChannelAnalysisResult

        % Registro auxiliar de transformações e operações não contempladas
        % explicitamente nas propriedades anteriores
        LOG = {}
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function fieldTemplate = getFieldTemplate(dataType, varargin)
            arguments
                dataType {mustBeMember(dataType, {'Measures:Level',                   ...
                                                  'Measures:BandWidth',               ...
                                                  'Measures:FCO',                     ...
                                                  'Measures:FBO',                     ...
                                                  'ChannelAssigned',                  ...
                                                  'Classification',                   ...
                                                  'DefaultAlgorithm: Detection',      ...
                                                  'DefaultAlgorithm: Classification', ...
                                                  'DefaultAlgorithm: Occupancy',      ...
                                                  'DefaultAlgorithm: BandWidth'})}
            end

            arguments (Repeating)
                varargin
            end

            switch dataType
                case 'Measures:Level'
                    fieldTemplate = struct('FreqCenter_Min',      {},  ...
                                           'FreqCenter_Mean',     {},  ...
                                           'FreqCenter_Max',      {},  ...
                                           'Channel_Min',         {},  ...
                                           'Channel_Mean',        {},  ...
                                           'Channel_Max',         {});

                case 'Measures:BandWidth'
                    fieldTemplate = struct('Min',                 {},  ...
                                           'Mean',                {},  ...
                                           'Max',                 {});

                case 'Measures:FCO'
                    fieldTemplate = struct('FreqCenter_Infinite', {},  ...
                                           'Channel_Infinite',    {},  ...
                                           'Channel_Finite_Min',  {},  ...
                                           'Channel_Finite_Mean', {},  ...
                                           'Channel_Finite_Max',  {});

                case 'Measures:FBO'
                    fieldTemplate = struct('Channel_Min',         {},  ...
                                           'Channel_Mean',        {},  ...
                                           'Channel_Max',         {});

                case 'ChannelAssigned'
                    chAssigned    = util.emissionChannel(varargin{:});
                    fieldTemplate = struct('autoSuggested', chAssigned, ...
                                           'userModified',  chAssigned);

                case 'Classification'
                    emissionInfo  = util.Classification.run(varargin{:});
                    fieldTemplate = struct('autoSuggested', emissionInfo, ...
                                           'userModified',  emissionInfo);

                case 'DefaultAlgorithm: Detection'
                    manualMode = 0;
                    parameters = struct('Distance_kHz', 25, ...
                                        'BW_kHz',       10, ...
                                        'Prominence1',  10, ...
                                        'Prominence2',  30, ...
                                        'meanOCC',      10, ...
                                        'maxOCC',       67);

                    if nargin >= 2
                        manualMode = varargin{1};
                    end

                    if nargin >= 3
                        parameters = varargin{2};
                    end

                    fieldTemplate = struct('ManualMode', manualMode,     ...
                                           'Algorithm', 'FindPeaks+OCC', ...
                                           'Parameters', parameters);

                case 'DefaultAlgorithm: Classification'
                    fieldTemplate = util.Classification.ParametersDefault;

                case 'DefaultAlgorithm: Occupancy'
                    fieldTemplate = RF.Occupancy.ParametersDefault();

                case 'DefaultAlgorithm: BandWidth'
                    fieldTemplate = [];
            end
        end
    end
end