classdef (Abstract) Constants

    properties (Constant)
        %-----------------------------------------------------------------%
        appName       = 'appAnalise'
        appVersion    = 'alpha_2.00.0'

        windowSize    = [1244, 660]
        windowMinSize = [ 950, 660]

        Interactions  = {'datacursor', 'zoomin', 'restoreview'}

        yMinLimRange  = 80 % Minimum y-Axis limit range
        yMaxLimRange  = 100 % Maximum y-Axis limit range

        specDataTypes = [1, 2, 4, 7, 60, 61, 63, 64, 67, 68, 167, 168, 1000, 1809];
        occDataTypes  = [8, 62, 65, 69];

        xDecimals     = 5
        floatDiffTol  = 1e-5

        nMaxWaterFallPoints   = 1474560
        nMaxPersistancePoints = 51200512 % nMaxPointsFSW * nMaxPersistanceOption (GUI) = 100001 * 512
        ElevationTolerance    = .85
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function [yUpLimit, normUnit] = yAxisUpLimit(unit)
            switch lower(unit)
                case 'dbm'
                    yUpLimit = -20; 
                    normUnit = 'dBm';
                
                case {'dbµv', 'dbμv', 'dbuv'}
                    yUpLimit =  87;
                    normUnit = 'dBµV';

                case {'dbµv/m', 'dbμv/m'}
                    yUpLimit = 100;
                    normUnit = 'dBµV/m';
            end
        end

        %-----------------------------------------------------------------%
        function d = english2portuguese()
            names  = ["Algorithm", ...
                      "AntennaHeight", ...
                      "Azimuth", ...
                      "Band", ...
                      "BitsPerSample", ...
                      "ChannelBW", ...
                      "Count", ...
                      "DataPoints", ...
                      "Description", ...
                      "Detection", ...
                      "Distance", ...
                      "Elevation", ...
                      "Family", ...
                      "File", ...
                      "GpsStatus", ...
                      "NumFiles", ...
                      "FileVersion", ...
                      "Frequency", ...
                      "FreqStart", ...
                      "FreqStop", ...
                      "gpsType", ...
                      "Height", ...
                      "Installation", ...
                      "IntegrationFactor", ...
                      "IntegrationTime", ...
                      "LevelUnit", ...
                      "Location", ...
                      "LocationSource", ...
                      "Memory", ...
                      "MetaData", ...
                      "Method", ...
                      "Name", ...
                      "nData", ...
                      "NumSweeps", ...
                      "Observation", ...
                      "ObservationSamples", ...
                      "ObservationTime", ...
                      "ObservationType", ...
                      "Occupancy", ...
                      "Parameters", ...
                      "Polarization", ...
                      "Position", ...
                      "Prominence", ...
                      "Receiver", ...
                      "Regulatory", ...
                      "Resolution", ...
                      "RevisitTime", ...
                      "RiskLevel", ...
                      "RFMode", ...
                      "Service", ...
                      "Sync", ...
                      "Station", ...
                      "StepWidth", ...
                      "switchPort", ...
                      "Target", ...
                      "Task", ...
                      "taskType", ...
                      "Type", ...
                      "TraceIntegration", ...
                      "TraceMode", ...
                      "TrackingMode", ...
                      "FreqCenterLevelRange", ...
                      "IntegratedEmissionLevelRange", ...
                      "FreqCenterCumulativeOccupancy", ...
                      "EmissionCumulativeOccupancy", ...
                      "EmissionType"];

            values = ["Algoritmo", ...
                      "Altura da antena", ...
                      "Azimute", ...
                      "Banda", ...
                      "Codificação", ...
                      "Largura", ...
                      "Qtd. amostras", ...
                      "Pontos por varredura", ...
                      "Descrição", ...
                      "Detecção", ...
                      "Distância", ...
                      "Elevação", ...
                      "Família", ...
                      "Arquivo", ...
                      "Situação", ...
                      "Qtd. arquivos", ...
                      "Arquivo", ...
                      "Frequência", ...
                      "Frequência inicial", ...
                      "Frequência final", ...
                      "GPS", ...
                      "Altura", ...
                      "Instalação", ...
                      "Integração", ...
                      "Tempo de integração", ...
                      "Unidade", ...
                      "Localidade", ...
                      "Fonte", ...
                      "Memória", ...
                      "Metadados", ...
                      "Método", ...
                      "Nome", ...
                      "Qtd. fluxos", ...
                      "Qtd. varreduras", ...
                      "Observação", ...
                      "Amostras a coletar", ...
                      "Observação", ...
                      "Tipo de observação", ...
                      "Ocupação", ...
                      "Parâmetros", ...
                      "Polarização", ...
                      "Posição", ...
                      "Proeminência", ...
                      "Receptor", ...
                      "Situação", ...
                      "Resolução", ...
                      "Tempo de revisita", ...
                      "Potencial lesivo", ...
                      "Modo RF", ...
                      "Serviço", ...
                      "Sincronismo", ...
                      "Estação", ...
                      "Passo da varredura", ...
                      "Porta da matriz", ...
                      "Alvo", ...
                      "Tarefa", ...
                      "Tipo de tarefa", ...
                      "Tipo", ...
                      "Integração", ...
                      "Traço", ...
                      "Modo de apontamento", ...
                      "Nível na frequência central", ...
                      "Nível na faixa  da  emissão", ...
                      "Ocupação na frequência central", ...
                      "Ocupação na faixa  da  emissão", ...
                      "Tipo de emissão"];
        
            d = dictionary(names, values);
        end
    end
end